### ISSUE TITLE
Add links to guides

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-cloudservices#3]
When integration guide will be ready we should add links in docs to the `cloudservices.tokenUrl`.

**Comment by Reinmar** [comment]
Which guide do you mean?

**Comment by pjasiun** [comment]
This one https://docs.ckeditor.com/cs/latest/guides/token-endpoints/tokenendpoint.html

**Comment by Reinmar** [comment]
ok, I'll handle this.

**Comment by Reinmar** [comment]
I pushed `t/3` but unfortunately it's blocked by https://github.com/cksource/umberto/issues/498.
